# Generated by Django 3.0.8 on 2020-07-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axisUsers', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awardId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
