# Generated by Django 3.1 on 2020-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisUsers', '0002_auto_20200811_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='awardType',
            field=models.IntegerField(default=0),
        ),
    ]
