# Generated by Django 3.1 on 2020-08-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisUsers', '0002_auto_20200817_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axisawards',
            name='awardName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
