# Generated by Django 3.0.8 on 2020-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisUsers', '0003_auto_20200724_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
