# Generated by Django 3.0.8 on 2020-07-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisUsers', '0004_auto_20200725_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membershipDate',
        ),
    ]
