# Generated by Django 3.0.8 on 2020-07-26 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=200)),
                ('postSlug', models.SlugField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[('0', 'Draft/Not Published'), ('1', 'Published')], default=0)),
                ('content', models.TextField()),
                ('popularity', models.BigIntegerField(default=0)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('postAuthor', models.ForeignKey(default='AnynomousAxisUser', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['popularity'],
            },
        ),
    ]
