# Generated by Django 3.1 on 2020-08-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-popularity']},
        ),
    ]
