# Generated by Django 3.1 on 2020-09-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='parentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='axisPosts.postcomments'),
        ),
    ]
