# Generated by Django 3.1 on 2020-08-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomments',
            options={'ordering': ['-popularity']},
        ),
        migrations.AlterField(
            model_name='commentreactions',
            name='commentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.postcomments'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.post'),
        ),
        migrations.AlterField(
            model_name='postreactions',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.post'),
        ),
    ]
