# Generated by Django 3.0.8 on 2020-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postSlug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
