# Generated by Django 3.0.8 on 2020-07-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('axisPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='axisStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='postReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.Post')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField()),
                ('parentId', models.IntegerField()),
                ('comment', models.TextField()),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('commentAuthor', models.ForeignKey(default='AnynomousAxisUser', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='commentReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField()),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axisPosts.postComments')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
