# Generated by Django 3.1 on 2020-09-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0002_auto_20200901_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='axisPosts.postcomments'),
        ),
    ]
