# Generated by Django 3.0.8 on 2020-08-03 07:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0002_auto_20200803_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postSlug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
