# Generated by Django 3.0.8 on 2020-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='axisPosts/posts/images'),
        ),
    ]
