# Generated by Django 3.0.8 on 2020-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0003_auto_20200726_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
