# Generated by Django 3.1 on 2020-09-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0003_auto_20200901_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='parentId',
            field=models.IntegerField(default=0),
        ),
    ]
