# Generated by Django 3.0.8 on 2020-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0004_auto_20200803_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
