# Generated by Django 3.0.8 on 2020-08-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0004_auto_20200831_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
