# Generated by Django 3.0.8 on 2020-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0004_postcomments_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreactions',
            name='commentId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='postId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='postreactions',
            name='postId',
            field=models.BigIntegerField(),
        ),
    ]
