# Generated by Django 3.0.8 on 2020-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0005_auto_20200726_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
