# Generated by Django 3.0.8 on 2020-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0005_auto_20200804_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
