# Generated by Django 3.1 on 2020-09-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0006_auto_20200901_1207'),
        ('axisPosts', '0005_auto_20200831_0330'),
    ]

    operations = [
    ]
