# Generated by Django 3.1 on 2020-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axisPosts', '0007_merge_20200902_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
